version: '3'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: mediumuser
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: medium_db
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
