# fly.toml app configuration file generated for medium-1-nest-js on 2023-08-24T12:35:42+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "medium-1-nest-js"
primary_region = "waw"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[deploy]
  release_command = "npm run migration:run:js"

[env]
  JWT_SECRET = "secret"